# This file contains environment-specific credentials and settings.
# Add your credentials here in plain text - Rails will encrypt them automatically.

# Example:
# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: c1142f298c9d280516ab7439d73027dfc1142f298c9d280516ab7439d73027df